#= require "../../bower_components/angular/angular.js"
#= require "../../bower_components/angular-ui-router/release/angular-ui-router.js"
#= require "../../bower_components/lodash/dist/lodash.js"
#= require "../../bower_components/restangular/dist/restangular.js"
#= require "../../bower_components/angular-tree-control/angular-tree-control.js"
#= require "../../bower_components/angular-bootstrap/ui-bootstrap-tpls.js"
